In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [14]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [15]:
df['Spam'] = df.Category.apply(lambda x:1 if x == 'spam' else 0)

In [16]:
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [17]:
from sklearn.model_selection import train_test_split as tts

X_train, X_test, y_train, y_test = tts(df.Message, df.Spam, test_size=0.2)

In [51]:
X_train

3998    Bored housewives! Chat n date now! 0871750.77....
951            Awesome, lemme know whenever you're around
1531                        I think chennai well settled?
1639                Great comedy..cant stop laughing da:)
3799    Feb  &lt;#&gt;  is "I LOVE U" day. Send dis to...
                              ...                        
1699    Free msg. Sorry, a service you ordered from 81...
1709    How's my loverboy doing ? What does he do that...
4685    My life Means a lot to me, Not because I love ...
2466                       S.i think he is waste for rr..
3572                       But you dint in touch with me.
Name: Message, Length: 4457, dtype: object

In [25]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4457,), (1115,), (4457,), (1115,))

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7772 sparse matrix of type '<class 'numpy.int64'>'
	with 58979 stored elements in Compressed Sparse Row format>

In [48]:
X_train_cv.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [36]:
X_train_cv.shape

(4457, 7772)

In [61]:
v.get_feature_names_out()[3559]

'housewives'

In [40]:
v.vocabulary_

{'bored': 1458,
 'housewives': 3559,
 'chat': 1769,
 'date': 2197,
 'now': 4876,
 '0871750': 135,
 '77': 629,
 '11': 275,
 'bt': 1562,
 'national': 4737,
 'rate': 5610,
 '10p': 272,
 'min': 4510,
 'only': 4973,
 'from': 3056,
 'landlines': 4046,
 'awesome': 1186,
 'lemme': 4110,
 'know': 3997,
 'whenever': 7508,
 'you': 7736,
 're': 5623,
 'around': 1085,
 'think': 6872,
 'chennai': 1793,
 'well': 7478,
 'settled': 6085,
 'great': 3276,
 'comedy': 1930,
 'cant': 1664,
 'stop': 6527,
 'laughing': 4071,
 'da': 2166,
 'feb': 2829,
 'lt': 4288,
 'gt': 3304,
 'is': 3781,
 'love': 4264,
 'day': 2204,
 'send': 6058,
 'dis': 2364,
 'to': 6959,
 'all': 926,
 'ur': 7226,
 'valued': 7272,
 'frnds': 3048,
 'evn': 2709,
 'me': 4435,
 'if': 3639,
 'comes': 1931,
 'back': 1207,
 'll': 4198,
 'married': 4398,
 'person': 5190,
 'luv': 4302,
 'ignore': 3643,
 'will': 7546,
 'lose': 4247,
 'evr': 2711,
 'finally': 2883,
 'the': 6842,
 'match': 4409,
 'heading': 3411,
 'towards': 7026,
 'draw': 2466,
 'as

In [49]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
np.where(X_train_np[0]!=0)

(array([ 135,  272,  275,  629, 1458, 1562, 1769, 2197, 3056, 3559, 4046,
        4510, 4737, 4876, 4973, 5610], dtype=int64),)

In [60]:
X_train[3998]

'Bored housewives! Chat n date now! 0871750.77.11! BT-national rate 10p/min only from landlines!'

In [59]:
X_train_np[0][3559]

1

In [62]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [66]:
X_test_cv = v.transform(X_test.values)

In [67]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       968
           1       0.97      0.96      0.97       147

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [68]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

email_count = v.transform(emails)
model.predict(email_count)

array([0, 1], dtype=int64)

In [74]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [76]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [82]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       968
           1       0.97      0.96      0.97       147

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

