In [6]:
import tensorflow_hub as hub
import tensorflow_text as text

In [7]:
import tensorflow as tf

In [8]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

preprocess our model

In [9]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

OSError: SavedModel file does not exist at: C:\Users\nitis\AppData\Local\Temp\tfhub_modules\602d30248ff7929470db09f7385fc895e9ceb4c0\{saved_model.pbtxt|saved_model.pb}

In [7]:
text_test = ['nice movie indeed', 'I love python programming']
text_preprocessed = bert_preprocess_model(text_test)

In [10]:
text_preprocessed.keys()

dict_keys(['input_mask', 'input_word_ids', 'input_type_ids'])

In [11]:
text_preprocessed['input_mask'] # five 1's for "nice movie indeed" is first 1 is for CLS and last 1 is for SEP and others in the middle are for the actual sentence and rest are the padding 

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [14]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [15]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

below will generate word/sentence embeddings

In [16]:
bert_model = hub.KerasLayer(encoder_url)
bert_result = bert_model(text_preprocessed)
bert_result.keys()

dict_keys(['sequence_output', 'pooled_output', 'default', 'encoder_outputs'])

## for any embedding may it for each word or each sentence, it a generates 768-length embedding vector

In [34]:
bert_result['pooled_output'] # this is a embedding for each sentence it generates 768 outputs 

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917743 , -0.21411934,  0.4976949 , ...,  0.24465166,
        -0.4733449 ,  0.81758726],
       [-0.9171231 , -0.4793518 , -0.78656983, ..., -0.6175176 ,
        -0.7102687 ,  0.92184293]], dtype=float32)>

In [33]:
bert_result['default'] # pooled is the default output which is for each sentence 

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917743 , -0.21411934,  0.4976949 , ...,  0.24465166,
        -0.4733449 ,  0.81758726],
       [-0.9171231 , -0.4793518 , -0.78656983, ..., -0.6175176 ,
        -0.7102687 ,  0.92184293]], dtype=float32)>

In [28]:
bert_result['encoder_outputs'] # this is a embedding for each word in a sentence, there are 12 outputs coz of 12 encoder layers, each output is for each layer

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901427,  0.00644756, -0.03614959, ...,  0.04999617,
           0.06149195, -0.02657554],
         [ 1.1753383 ,  1.2140788 ,  1.156998  , ...,  0.11634377,
          -0.3585539 , -0.4049023 ],
         [ 0.03859045,  0.5386999 , -0.21089773, ...,  0.21858215,
           0.7260168 , -1.1158609 ],
         ...,
         [-0.07587016, -0.2542193 ,  0.7075512 , ...,  0.5054201 ,
          -0.18878648,  0.15028323],
         [-0.16066599, -0.28089675,  0.5759705 , ...,  0.5275856 ,
          -0.11141355,  0.0288752 ],
         [-0.04428156, -0.20279586,  0.59093523, ...,  0.8133835 ,
          -0.3907579 , -0.02601741]],
 
        [[ 0.18903571,  0.02752551, -0.06513739, ..., -0.00620209,
           0.15053877,  0.03165431],
         [ 0.59161484,  0.75891393, -0.07240683, ...,  0.6190397 ,
           0.8292891 ,  0.16161966],
         [ 1.4460826 ,  0.4460267 ,  0.40990284, ...,  0.48255897,
           0.6269113 ,  0.13

In [29]:
bert_result['sequence_output'] # final output for each word in a sentence 

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292042,  0.08567819,  0.14476846, ..., -0.09677091,
          0.08722158,  0.07711089],
        [ 0.17839484, -0.19006062,  0.50349456, ..., -0.05869824,
          0.3271712 , -0.15578577],
        [ 0.18701512, -0.43388787, -0.4887515 , ..., -0.1550272 ,
          0.0014518 , -0.24471004],
        ...,
        [ 0.12083051,  0.12884259,  0.46453547, ...,  0.0737555 ,
          0.17441949,  0.16522136],
        [ 0.07967859, -0.01190698,  0.50225425, ...,  0.13777778,
          0.2100223 ,  0.00624579],
        [-0.07212703, -0.28303495,  0.5903335 , ...,  0.4755193 ,
          0.16668479, -0.08920302]],

       [[-0.07900573,  0.36335123, -0.2110158 , ..., -0.17183736,
          0.1629973 ,  0.67242646],
        [ 0.2788349 ,  0.4371635 , -0.35764754, ..., -0.04463583,
          0.38315123,  0.5887979 ],
        [ 1.2037661 ,  1.072702  ,  0.48408687, ...,  0.24921006,
          0.4073092 ,  0.404818  ],
        ...,

In [32]:
bert_result['encoder_outputs'][-1] == bert_result['sequence_output'] # the last encoder output is the final embedding vector output

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>