In [1]:
import tensorflow as tf

In [2]:
daily_sales_num = [25, 13, -90, 46, -2, 74, 102, -159]

In [3]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_num) # loading a pyhton list into tf datasets 
tf_dataset # it gives us an object which we can iterate through

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [4]:
for sales in tf_dataset:
    print(sales)

tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)
tf.Tensor(-90, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(-2, shape=(), dtype=int32)
tf.Tensor(74, shape=(), dtype=int32)
tf.Tensor(102, shape=(), dtype=int32)
tf.Tensor(-159, shape=(), dtype=int32)


In [5]:
for sales in tf_dataset:
    print(sales.numpy()) # the default object is tensor .numpy() is for converting it into numpy object

25
13
-90
46
-2
74
102
-159


In [6]:
for sales in tf_dataset.as_numpy_iterator(): # .as_numpy_iterator() is same like .numpy()
    print(sales)

25
13
-90
46
-2
74
102
-159


In [7]:
for sales in tf_dataset.take(3): # first 3 numbers
    print(sales.numpy())

25
13
-90


In [8]:
tf_dataset = tf_dataset.filter(lambda x: x>0) # filtering numbers which are less than 0
for sales in tf_dataset:
    print(sales.numpy())

25
13
46
74
102


In [9]:
tf_dataset = tf_dataset.map(lambda x: x*82) # converting dollar to inr 
for sales in tf_dataset:
    print(sales.numpy())

2050
1066
3772
6068
8364


In [10]:
tf_dataset = tf_dataset.shuffle(3) # shuffling the numbers by giving a buffer value
for sales in tf_dataset:
    print(sales.numpy())

2050
3772
8364
6068
1066


In [11]:
for sales in tf_dataset.batch(2): # making batches of them
    print(sales.numpy())

[2050 3772]
[6068 8364]
[1066]


In [12]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_num)
tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*82).shuffle(3).batch(2) # doing all the operations in one line
for sales in tf_dataset:
    print(sales.numpy())

[3772 2050]
[8364 6068]
[1066]


In [13]:
image_ds = tf.data.Dataset.list_files('images/*/*', shuffle = False) # loading all file paths in tf dataset
image_ds

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>

In [14]:
for sales in image_ds.take(3):
    print(sales.numpy())

b'images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg'
b'images\\cat\\7 Foods Your Cat Can_t Eat.jpg'
b'images\\cat\\A cat appears to have caught the....jpg'


In [17]:
image_ds = image_ds.shuffle(200)
for sales in image_ds.take(10):
    print(sales.numpy())

b'images\\dog\\The US Army is testing augmented....jpg'
b'images\\dog\\Trained dogs can smell coronavirus in....jpg'
b'images\\cat\\Giving cats food with an antibody may....jpg'
b'images\\cat\\What to do if your cat is marking....jpg'
b'images\\dog\\why dogs understand our body language....jpg'
b'images\\dog\\How Many Dog Breeds Are There_ _ Hill_s Pet.jpg'
b'images\\cat\\The Joys of Owning a Cat - HelpGuide.org.jpg'
b'images\\dog\\Service Dogs from Southeastern Guide Dogs.jpg'
b'images\\dog\\Calculate Your Dog_s Age With This New....jpg'
b'images\\dog\\Common Dog Breeds and Their Health Issues.jpg'


In [19]:
class_names = ['cat', 'dog']

In [21]:
image_count = len(image_ds)
image_count

130

In [23]:
train_size = int(image_count*0.8)

train_ds = image_ds.take(train_size)
test_ds = image_ds.skip(train_size) # skip is like skipping the input size and taking all afterthat

In [25]:
len(test_ds)

26

In [27]:
s = 'images\\dog\\The US Army is testing augmented....jpg'
s.split('\\') [-2]

'dog'

In [40]:
def get_label(file_path):
    import os
    label = tf.strings.split(file_path, os.path.sep)[-2] # doing splitting by tf module because as is a tensor object
    return label

In [41]:
get_lable('images\\dog\\The US Army is testing augmented....jpg')

<tf.Tensor: shape=(), dtype=string, numpy=b'dog'>

In [42]:
for label in train_ds.map(get_lable):
    print(label.numpy())

b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'cat'
b'dog'
b'cat'
b'dog'
b'dog'
b'cat'
b'dog'
b'dog'
b'cat'
b'dog'
b'dog'
b'cat'
b'dog'
b'cat'
b'dog'
b'dog'
b'dog'
b'dog'
b'cat'
b'cat'
b'dog'
b'cat'
b'dog'
b'dog'
b'dog'
b'cat'
b'cat'
b'dog'
b'cat'
b'dog'
b'cat'
b'cat'
b'cat'
b'dog'
b'cat'
b'dog'
b'dog'
b'cat'
b'dog'
b'dog'
b'cat'
b'dog'
b'dog'
b'dog'
b'dog'
b'cat'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'cat'
b'dog'
b'dog'
b'cat'
b'dog'
b'dog'
b'dog'
b'dog'
b'cat'
b'dog'
b'dog'
b'dog'
b'dog'
b'cat'
b'dog'
b'cat'
b'dog'
b'dog'
b'dog'
b'cat'
b'dog'
b'dog'
b'cat'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'cat'


In [43]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path) # loading the raw image through file path
    img = tf.image.decode_jpeg(img) # decoding the image 
    img = tf.image.resize(img, [128, 128]) # resizing the image
    return img, label

In [44]:
for img, label in train_ds.map(process_image):
    print(label.numpy())
    print(img.numpy())

b'cat'
[[[ 70.        59.        53.      ]
  [ 71.78052   61.780518  59.780518]
  [ 72.93628   64.93628   61.93628 ]
  ...
  [ 45.398438  38.960938  20.679688]
  [ 47.89917   44.89917   27.89917 ]
  [ 55.41382   53.41382   41.41382 ]]

 [[ 70.76636   59.766357  53.766357]
  [ 73.32031   63.320312  61.320312]
  [ 73.80884   65.80884   62.808838]
  ...
  [ 65.29736   59.679688  47.679688]
  [ 68.078125  64.078125  52.757812]
  [ 74.48511   71.48511   62.485107]]

 [[ 70.65625   59.65625   53.65625 ]
  [ 76.00415   66.00415   64.00415 ]
  [ 73.5625    65.5625    62.5625  ]
  ...
  [ 84.39844   80.39844   69.96094 ]
  [ 88.53125   85.53125   78.53125 ]
  [ 93.10034   90.10034   83.10034 ]]

 ...

 [[ 38.56372   35.56372   30.56372 ]
  [ 46.0271    41.0271    37.0271  ]
  [ 46.243896  37.318604  32.28125 ]
  ...
  [187.54858  173.58594  190.58594 ]
  [185.76562  171.89844  188.89844 ]
  [180.73438  170.       186.13281 ]]

 [[ 40.640625  35.640625  31.640625]
  [ 54.        46.        43. 

[[[129.03906  113.03906   77.03906 ]
  [131.       115.        79.      ]
  [129.875    113.875     79.875   ]
  ...
  [115.99756  102.99756   93.99756 ]
  [105.54053   96.54053   87.54053 ]
  [ 94.367676  85.367676  76.367676]]

 [[129.23438  113.234375  77.234375]
  [131.       115.        79.      ]
  [129.875    113.875     79.875   ]
  ...
  [117.82764  104.82764   95.82764 ]
  [107.        98.        89.      ]
  [ 98.72803   89.72803   80.72803 ]]

 [[129.8125   113.8125    77.8125  ]
  [131.80469  115.80469   79.80469 ]
  [131.       115.        81.      ]
  ...
  [116.183105 103.183105  94.183105]
  [106.125     97.125     88.125   ]
  [ 98.1875    89.1875    80.1875  ]]

 ...

 [[141.20312  124.203125  98.203125]
  [142.63281  125.63281   99.63281 ]
  [143.       128.        99.      ]
  ...
  [192.       157.       119.      ]
  [190.36719  155.36719  117.36719 ]
  [191.4585   156.4585   118.458496]]

 [[143.09229  126.092285 100.04834 ]
  [146.4375   129.4375   103.33496 ]


InvalidArgumentError: Unknown image file format. One of JPEG, PNG, GIF, BMP required.
	 [[{{node DecodeJpeg}}]] [Op:IteratorGetNext]

In [45]:
train_ds = train_ds.map(process_image)

In [46]:
def scale(img, label):
    return img/255, label

In [47]:
train_ds = train_ds.map(scale)

In [50]:
for img, label in train_ds.take(3):
    print(label.numpy())
    print(img.numpy()[0][0])

b'dog'
[0.52071077 0.69644606 0.88394606]
b'cat'
[0.2784314  0.4392157  0.29803923 0.        ]
b'dog'
[0.60398287 0.6628064  0.6510417 ]
