In [2]:
import numpy as np 
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

iris = load_iris()

In [35]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter = 1000), iris.data, iris.target) 

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [33]:
cross_val_score(SVC(C =100, kernel = 'linear'), iris.data, iris.target)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [34]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])